openapi: 3.0.3
info:
  title: Contract first example - OpenAPI 3.1
  description: >-
    An example of contract first. It might be a good idé to use [The Swagger
    editor](https://editor.swagger.io) to generate to openapi specification
    file.
  contact:
    email: carl.svensen@cygni.se
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080
tags:
  - name: person
    description: Everything about a Person
paths:
  /persons:
    get:
      tags:
        - person
      summary: Finds all registered Persons
      description: A more detailed description of the Persons that are available
      operationId: getPersons
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '429':
          description: Too high load. Try again later.
        '502':
          description: Something wrong with the network
        '503':
          description: Something wrong with the server
  /persons/{id}:
    get:
      tags:
        - person
      summary: Find person by id
      description: Returns a single person
      operationId: getPersonById
      parameters:
        - name: id
          in: path
          description: ID of person to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Invalid id supplied
        '404':
          description: Person not found
    post:
      tags:
        - person
      summary: Updates a person
      description: ''
      operationId: updatePerson
      parameters:
        - name: id
          in: path
          description: id of person that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
        - name: firstname
          in: query
          description: Name of id that needs to be updated
          schema:
            type: string
        - name: lastname
          in: query
          description: Status of pet that needs to be updated
          schema:
            type: string
      responses:
        '400':
          description: Invalid id supplied
        '404':
          description: Person not found
        '405':
          description: Invalid input
components:
  schemas:
    Person:
      required:
        - id
        - firstname
        - lastname
        - address
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        firstname:
          type: string
          example: Navn
        lastname:
          type: string
          example: Navnesen
        address:
          type: string
          example: Address 1a
